config/routes.rb
Rails.application.routes.draw do
  resources :peliculas
  root 'peliculas#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pelicula.rb
class Pelicula < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/peliculas_controller.rb
class PeliculasController < ApplicationController
  before_action :set_pelicula, only: [:show, :edit, :update, :destroy]

  # GET /peliculas
  # GET /peliculas.json
  def index
    @peliculas = Pelicula.all
  end

  # GET /peliculas/1
  # GET /peliculas/1.json
  def show
  end

  # GET /peliculas/new
  def new
    @pelicula = Pelicula.new
  end

  # GET /peliculas/1/edit
  def edit
  end

  # POST /peliculas
  # POST /peliculas.json
  def create
    @pelicula = Pelicula.new(pelicula_params)

    respond_to do |format|
      if @pelicula.save
        format.html { redirect_to @pelicula, notice: 'Pelicula was successfully created.' }
        format.json { render :show, status: :created, location: @pelicula }
      else
        format.html { render :new }
        format.json { render json: @pelicula.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /peliculas/1
  # PATCH/PUT /peliculas/1.json
  def update
    respond_to do |format|
      if @pelicula.update(pelicula_params)
        format.html { redirect_to @pelicula, notice: 'Pelicula was successfully updated.' }
        format.json { render :show, status: :ok, location: @pelicula }
      else
        format.html { render :edit }
        format.json { render json: @pelicula.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /peliculas/1
  # DELETE /peliculas/1.json
  def destroy
    @pelicula.destroy
    respond_to do |format|
      format.html { redirect_to peliculas_url, notice: 'Pelicula was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pelicula
      @pelicula = Pelicula.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pelicula_params
      params.require(:pelicula).permit(:name, :stars, :main_actor, :year, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/peliculas_helper.rb
module PeliculasHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Project</title>
    <%= csrf_meta_tags %>

  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/peliculas/_form.html.erb
<%= form_with(model: pelicula, local: true) do |form| %>
  <% if pelicula.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pelicula.errors.count, "error") %> prohibited this pelicula from being saved:</h2>

      <ul>
      <% pelicula.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :pelicula_name %>
  </div>

  <div class="field">
    <%= form.label :stars %>
    <%= form.number_field :stars, id: :pelicula_stars %>
  </div>

  <div class="field">
    <%= form.label :main_actor %>
    <%= form.text_field :main_actor, id: :pelicula_main_actor %>
  </div>

  <div class="field">
    <%= form.label :year %>
    <%= form.number_field :year, id: :pelicula_year %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :pelicula_description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/peliculas/edit.html.erb
<h1>Editing Pelicula</h1>

<%= render 'form', pelicula: @pelicula %>

<%= link_to 'Show', @pelicula %> |
<%= link_to 'Back', peliculas_path %>

app/views/peliculas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Peliculas</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Stars</th>
      <th>Main actor</th>
      <th>Year</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @peliculas.each do |pelicula| %>
      <tr>
        <td><%= pelicula.name %></td>
        <td><%= pelicula.stars %></td>
        <td><%= pelicula.main_actor %></td>
        <td><%= pelicula.year %></td>
        <td><%= pelicula.description %></td>
        <td><%= link_to 'Show', pelicula %></td>
        <td><%= link_to 'Edit', edit_pelicula_path(pelicula) %></td>
        <td><%= link_to 'Destroy', pelicula, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pelicula', new_pelicula_path %>

app/views/peliculas/new.html.erb
<h1>New Pelicula</h1>

<%= render 'form', pelicula: @pelicula %>

<%= link_to 'Back', peliculas_path %>

app/views/peliculas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @pelicula.name %>
</p>

<p>
  <strong>Stars:</strong>
  <%= @pelicula.stars %>
</p>

<p>
  <strong>Main actor:</strong>
  <%= @pelicula.main_actor %>
</p>

<p>
  <strong>Year:</strong>
  <%= @pelicula.year %>
</p>

<p>
  <strong>Description:</strong>
  <%= @pelicula.description %>
</p>

<%= link_to 'Edit', edit_pelicula_path(@pelicula) %> |
<%= link_to 'Back', peliculas_path %>